### ISSUE TITLE
Add Ability to Roll Build Tokens

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/harbor#12]
Add an authenticated endpoint that can recreate the build token for a Shipment Environment.

`POST /shipment/:Shipment/environment/:Environment/buildToken`?

**Comment by wilsonodk** [comment]
Planning on implementing as `PATCH /v1/shipment/:shipment/environment/:environment`

**Comment by jkurz** [comment]
Nice job Wilson. Closing this.
