### ISSUE TITLE
Ability to Delete an Entire Shipment Object.

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/harbor#4]
We could do this multiple ways.
1. Add a view for the top level Shipment.
   - This gives us a nice navigation and allows us to use breadcrumbs on the Command Bridge
   - This also allows us to edit Env Vars on the Shipment level and make it obvious
   - This gives us the ability to change the group at the Shipment level and make it obvious
2. If there are no more environments left when deleting an environment, then also delete the shipment level object.

**Comment by wilsonodk** [comment]
@jkurz What do you mean by "Be not so obvious:"

**Comment by jkurz** [comment]
That doesn't make sense. I did not write that.

**Comment by wilsonodk** [comment]
Yes you did. https://github.com/turnerlabs/harbor-ui/issues/4

**Comment by jkurz** [comment]
Completed by @wilsonodk
