### ISSUE TITLE
Add click link in UI to take you to your ELB/ALB

### ISSUE THREAD

**Issue by mickeyyawn** [turnerlabs/harbor#46]
In UI, give the user the ability to navigate to the their ELB/ALB.  This is based on a conversation with John/Jason/James. Maybe add a tab with commands to manage their load balancer.

**Comment by jkurz** [comment]
Instead of adding a link directly to the aws console, which would require them be logged in either via saml or some other way, we just put the lb id on the command bridge page in the lb section.
