### ISSUE TITLE
Adding History view for each Shipment

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/harbor#5]
There is already a history application that shows the audit trail for each Shipment. https://github.com/turnerlabs/harbor-audit

Add a link to this running application for each Shipment, so users can easily see their logs and changes.

**Comment by jkurz** [comment]
i'd like to deeplink into this application via /product/environment conventions in the URL.

This would allow for us to be able to just have a link from a shipment to it's audittrail, as well as being able to share links directly to a shipment's audit trail.

**Comment by jkurz** [comment]
we are going to just do this with #28 and add it into harbor-ui. We are also going to add it into harbor-compose. We don't need another UI to maintain.
