### ISSUE TITLE
Add readonly group in Argonaut so that all Harbor data/apis' can be hit

### ISSUE THREAD

**Issue by mickeyyawn** [turnerlabs/harbor#53]
This is needed by DOC and ISO so that they can add automation around Harbor apis for shipment analysis.  Specifically for ISO it's for reading audit data.

**Comment by jkurz** [comment]
ok, I will add an environment variable that allows for read-only groups, bypassing normal authz.

**Comment by jkurz** [comment]
PR to close this issue https://github.com/turnerlabs/shipit-api/pull/36

**Comment by jkurz** [comment]
This can be closed. There were 3 issues with getting this to work. Here are all of the merges that took place. 

https://github.com/turnerlabs/shipit-api/commit/481edbc40ea33a436ada0f4ac177992e488d97db
https://github.com/turnerlabs/shipit-api/commit/821af933ebd3f94bc333ebd06d8c2711913cd017
https://github.com/turnerlabs/shipit-api/commit/46a5b5cdfc3c5753cd2b86e599a128c57abd7770
