### ISSUE TITLE
Harbor Bulk API returns HTTP 200 when errors occur

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/harbor#6]
If any call errors when making a bulk request to Harbor UI we still return a 200. Maybe we should be returning a 500 if any errors occur. Maybe we should also roll back any changes that were made. This might make things simpler and easier for user to understand that if a single error occurs, it does not mean that everything failed. It means just that one piece of the Shipment failed.

Another possible solution to this is to just rewrite ShipIt to support bulk updates.

**Comment by wilsonodk** [comment]
1. Adding bulk to ShipIt is definitely the correct thing to do.
2. With how it currently works, we should be returning a 200, since at least some of the requests passed. Just need better documentation on what the return object holds. Additionally, in many cases it would be better to return a 4xx error (when the user supplied bad content that failed) rather than a 5xx error.
3. Rolling back would introduce even more complexity around results. Imagine a complex Shipment being passed to the API. Lets say that there are 20 calls that need to be made. The first 19 calls succeed, but then a DNS outage occurs, so the 20th call fails. The app now tries to revert, but the DNS error is still happening. Now all 19 of the revert calls fail. We then return to the user that 20 calls failed. However, the reality is that 19 were successful and one wasn't, and then 19 revert failed. You could of course code all of that in, but by the time you've done that, might as well have spent the time doing it correct in the first place (aka bulk added to ShipIt directly).

**Comment by wilsonodk** [comment]
## Originally posted by @jkurz 

I agree @wilsonodk 

If anything we should add some retry logic into the UI that will see an error occurred and retry for x number of times. Maybe we should also be more transparent about what's going on behind the scenes. Don't make it look like there were major issues and let the user know what failed, and give them a button to retry the individual failure.

**Comment by jkurz** [comment]
So since we are working on the bulk save feature in the UI now, can we leverage that logic to create an entire shipment and remove this bulk endpoint?

**Comment by jkurz** [comment]
Going to close this in favor of us doing all the work on integrating the bulk api into the ui.
